# MAN:SC
:kroki-fetch-diagram:
:imagesdir: media
:author: Alphastrick
:source-highlighter: rouge
:toc:
:sectnums:

## Introdution

The MAN:SC (MetArt-Network Scraper / Crawler) scrapes data from MAN-Pages.

## Features

- *Media Scraping*
    * [x] Model
    * [x] Gallery
    * [x] Movie
    * [x] Update
    * [ ] Blog Posts
    * [ ] Full Media Download (with credentials)
- *Media Crawling*
    * [ ] Model with Qualified Galleries
    * [ ] Model Relations
    * [ ] Using MetArt's search 
    * [ ] Top X Model
    * [ ] Top X Media
- *Data Export*
    * StdOut
        ** [x] JSON
        ** [x] CSV

## Module Architecture

[plantuml,arch,svg]
----
skinparam componentStyle uml2

package "mansc" as mansc {

    package "types" as types {
        rectangle "Model" as t_model
        rectangle "Media" as t_media
        rectangle "Gallery" as t_gallery
        rectangle "Movie" as t_movie
        t_media <|-- t_gallery
        t_media <|-- t_movie
    }

    component "urlbuilder" as urlbuilder

    package "scraper" as scraper {
        rectangle "Page" as page
        rectangle "ModelPage" as modelpage
        rectangle "GalleryPage" as gallerypage
        rectangle "MoviePage" as moviepage
        rectangle "UpdatePage" as updatepage
        page <-- modelpage
        page <-- moviepage
        page <-- gallerypage
        page <-- updatepage
    }

    package "storage" as storage {

        rectangle "CSVEngine" as csv
        rectangle "JSONEngine" as json

    }

}
----

## Usage

### CLI

.CLI Example 1: Scraping model information
[shell]
----
python3 mansc.py --Result csv --source MetArtX model "Michelle H"
----

Scraping information about _Michelle H_ from _MetArtX_ and writes it as _csv_ to stdout

.CLI Example 2: Scraping gallery information
[shell]
----
python3 mansc.py --Result json media -o "gallery" -m "Michelle H" -m "Patritcy A" -t "Maldezi" -d "2016-12-21"
----

Scraping information from _MetArt_ about _Michelle H_'s and _Patritcy A_'s and  gallery _Maldezi_ and writes it as _json_ to _stdout_.

### Module

If the included CLI interface of the scraper does not fit your requirements,
building a custom solution may does the job.

The module usage is straight forward and demonstrated on the scraping
of _Michelle H_'s data.

Before scraping the data, it's necessary to provide a valid url.
The module provides a simple solution to build the MAN urls.
In order to fetch model information, use the `urlbuilder.BuildModelUrl` function.

[python]
----
url = urlbuilder.BuildModelUrl(types.Source.MetArt, model="Michelle H")
----

There are also functions for galleries, movies, models, and updates.

The data itself is loaded by the `Page` object,

[python]
----
page = scraper.Page(url)
----

which is the argument to every scraper.

[python]
----
modelScraper = scraper.ModelScraper(page)
----

Now, the data is ready for further processing by accessing
it:

[python]
----
print(modelScraper.Model)
----

